# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HEOy7Oe3SAOclPhkzE66I7XdGOZXdedf
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Load the dataset
df = pd.read_csv("healthcare-dataset-stroke-data.csv")

print("Dataset shape:", df.shape)
print(df.head())

# Check missing values
print(df.isnull().sum())

# Remove ID because it is not useful for prediction
df.drop("id", axis=1, inplace=True)

# Fill missing BMI values with median
df["bmi"] = df["bmi"].fillna(df["bmi"].median())

# Convert categorical columns into numbers
le = LabelEncoder()

df["gender"] = le.fit_transform(df["gender"])
df["ever_married"] = le.fit_transform(df["ever_married"])
df["work_type"] = le.fit_transform(df["work_type"])
df["Residence_type"] = le.fit_transform(df["Residence_type"])
df["smoking_status"] = le.fit_transform(df["smoking_status"])

# Separate input and output
X = df.drop("stroke", axis=1)
y = df["stroke"]

# Split data into training and testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Scale the input values
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Convert into NumPy arrays
X_train = np.array(X_train)
X_test = np.array(X_test)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

print("Preprocessing completed!")