# -*- coding: utf-8 -*-
"""
EDA file.py — Exploratory Data Analysis for Stroke Prediction

Originally generated by Google Colab with basic preprocessing.
Upgraded to perform comprehensive EDA:

1. Dataset information (shape, dtypes, missing values, duplicates, uniques)
2. Target analysis (class distribution, imbalance ratio)
3. Numerical feature analysis (histograms, box plots)
4. Categorical feature analysis (count plots)
5. Bivariate analysis (stroke vs each feature)
6. Correlation heatmap
7. Class imbalance visualization

All plots saved to results/eda/

Original file is located at:
    https://colab.research.google.com/drive/1HEOy7Oe3SAOclPhkzE66I7XdGOZXdedf
"""

import pandas as pd
import numpy as np
import os

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns

# Set consistent plot style
sns.set_style('whitegrid')
plt.rcParams['figure.dpi'] = 150
plt.rcParams['font.size'] = 11


from config import EDA_DIR


def run_eda(df, output_dir=EDA_DIR):
    """
    Execute complete EDA pipeline and save all plots.

    Args:
        df: Raw DataFrame (after dropping 'id', before any preprocessing)
        output_dir: Directory to save EDA plots and summaries
    """
    os.makedirs(output_dir, exist_ok=True)

    print("=" * 70)
    print("EXPLORATORY DATA ANALYSIS")
    print("=" * 70)

    # ----------------------------------------------------------
    # 1. Dataset Information
    # ----------------------------------------------------------
    _dataset_info(df)

    # ----------------------------------------------------------
    # 2. Target Analysis
    # ----------------------------------------------------------
    _target_analysis(df, output_dir)

    # ----------------------------------------------------------
    # 3. Numerical Feature Analysis
    # ----------------------------------------------------------
    _numerical_analysis(df, output_dir)

    # ----------------------------------------------------------
    # 4. Categorical Feature Analysis
    # ----------------------------------------------------------
    _categorical_analysis(df, output_dir)

    # ----------------------------------------------------------
    # 5. Bivariate Analysis (stroke vs features)
    # ----------------------------------------------------------
    _bivariate_analysis(df, output_dir)

    # ----------------------------------------------------------
    # 6. Correlation Heatmap
    # ----------------------------------------------------------
    _correlation_analysis(df, output_dir)

    print(f"\n[eda] All EDA plots saved to {output_dir}/")
    print("=" * 70)


# ============================================================
# 1. Dataset Information
# ============================================================
def _dataset_info(df):
    """Print comprehensive dataset information."""
    print("\n--- Dataset Information ---")
    print(f"Shape: {df.shape}")
    print(f"Rows:  {df.shape[0]}")
    print(f"Cols:  {df.shape[1]}")

    print(f"\n--- Data Types ---")
    print(df.dtypes)

    print(f"\n--- Missing Values ---")
    missing = df.isnull().sum()
    missing_pct = (missing / len(df) * 100).round(2)
    missing_df = pd.DataFrame({'Count': missing, 'Percentage': missing_pct})
    print(missing_df[missing_df['Count'] > 0] if missing.sum() > 0 else "No missing values")
    print(f"Total missing: {missing.sum()}")

    print(f"\n--- Duplicate Records ---")
    dupes = df.duplicated().sum()
    print(f"Duplicate rows: {dupes}")

    print(f"\n--- Unique Values ---")
    print(df.nunique())

    print(f"\n--- Descriptive Statistics (Numerical) ---")
    print(df.describe().round(2))

    print(f"\n--- Descriptive Statistics (Categorical) ---")
    print(df.describe(include='object'))


# ============================================================
# 2. Target Analysis
# ============================================================
def _target_analysis(df, output_dir):
    """Analyze and visualize the target variable distribution."""
    print("\n--- Target Variable Analysis ---")

    stroke_counts = df['stroke'].value_counts()
    total = len(df)

    no_stroke = stroke_counts[0]
    stroke = stroke_counts[1]

    print(f"No Stroke (0): {no_stroke}  ({no_stroke/total*100:.2f}%)")
    print(f"Stroke (1):    {stroke}  ({stroke/total*100:.2f}%)")
    print(f"Imbalance Ratio: {no_stroke/stroke:.1f}:1")

    # Class imbalance bar chart + pie chart
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    colors = ['#4CAF50', '#F44336']

    # Count plot
    axes[0].bar(['No Stroke\n(0)', 'Stroke\n(1)'],
                [no_stroke, stroke], color=colors, edgecolor='black', linewidth=0.5)
    axes[0].set_title('Stroke Class Distribution (Counts)', fontsize=13, fontweight='bold')
    axes[0].set_ylabel('Count', fontsize=11)
    for i, v in enumerate([no_stroke, stroke]):
        axes[0].text(i, v + 50, str(v), ha='center', fontweight='bold', fontsize=12)

    # Percentage pie chart
    axes[1].pie([no_stroke, stroke],
                labels=['No Stroke', 'Stroke'],
                autopct='%1.1f%%',
                colors=colors,
                startangle=90,
                explode=(0, 0.1),
                textprops={'fontsize': 12})
    axes[1].set_title('Stroke Class Distribution (Percentage)', fontsize=13, fontweight='bold')

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, '01_target_distribution.png'), bbox_inches='tight')
    plt.close()


# ============================================================
# 3. Numerical Feature Analysis
# ============================================================
def _numerical_analysis(df, output_dir):
    """Generate histograms and box plots for numerical features."""
    print("\n--- Numerical Feature Analysis ---")

    num_features = ['age', 'avg_glucose_level', 'bmi']

    fig, axes = plt.subplots(2, 3, figsize=(18, 10))

    for i, col in enumerate(num_features):
        data = df[col].dropna()

        # Histogram + KDE
        axes[0, i].hist(data, bins=30, color='#2196F3', edgecolor='black',
                        alpha=0.7, density=True)
        data.plot(kind='kde', ax=axes[0, i], color='#F44336', linewidth=2)
        axes[0, i].set_title(f'{col} - Distribution', fontsize=12, fontweight='bold')
        axes[0, i].set_xlabel(col)
        axes[0, i].set_ylabel('Density')

        # Box plot
        bp = axes[1, i].boxplot(data, patch_artist=True, vert=True)
        bp['boxes'][0].set_facecolor('#4CAF50')
        bp['boxes'][0].set_alpha(0.7)
        axes[1, i].set_title(f'{col} - Box Plot', fontsize=12, fontweight='bold')
        axes[1, i].set_ylabel(col)

        # Print stats
        print(f"\n{col}:")
        print(f"  Mean:   {data.mean():.2f}")
        print(f"  Median: {data.median():.2f}")
        print(f"  Std:    {data.std():.2f}")
        print(f"  Min:    {data.min():.2f}")
        print(f"  Max:    {data.max():.2f}")
        print(f"  Skew:   {data.skew():.2f}")

    plt.suptitle('Numerical Feature Distributions', fontsize=15, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, '02_numerical_distributions.png'), bbox_inches='tight')
    plt.close()


# ============================================================
# 4. Categorical Feature Analysis
# ============================================================
def _categorical_analysis(df, output_dir):
    """Generate count plots for categorical features."""
    print("\n--- Categorical Feature Analysis ---")

    cat_features = ['gender', 'hypertension', 'heart_disease', 'ever_married',
                    'work_type', 'Residence_type', 'smoking_status']

    fig, axes = plt.subplots(3, 3, figsize=(20, 16))
    axes = axes.flatten()

    palette = sns.color_palette('Set2', 10)

    for i, col in enumerate(cat_features):
        counts = df[col].value_counts()
        axes[i].bar(range(len(counts)), counts.values, color=palette[:len(counts)],
                    edgecolor='black', linewidth=0.5)
        axes[i].set_xticks(range(len(counts)))
        axes[i].set_xticklabels(counts.index, rotation=30, ha='right')
        axes[i].set_title(f'{col}', fontsize=12, fontweight='bold')
        axes[i].set_ylabel('Count')

        # Add value labels
        for j, v in enumerate(counts.values):
            axes[i].text(j, v + 20, str(v), ha='center', fontsize=9)

        print(f"\n{col}:")
        for val, cnt in counts.items():
            print(f"  {val}: {cnt} ({cnt/len(df)*100:.1f}%)")

    # Hide unused subplots
    for j in range(len(cat_features), len(axes)):
        axes[j].set_visible(False)

    plt.suptitle('Categorical Feature Distributions', fontsize=15, fontweight='bold', y=1.01)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, '03_categorical_distributions.png'), bbox_inches='tight')
    plt.close()


# ============================================================
# 5. Bivariate Analysis
# ============================================================
def _bivariate_analysis(df, output_dir):
    """Analyze relationships between stroke and key features."""
    print("\n--- Bivariate Analysis (Stroke vs Features) ---")

    # --- Numerical features vs stroke ---
    num_features = ['age', 'avg_glucose_level', 'bmi']

    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    colors = ['#4CAF50', '#F44336']

    for i, col in enumerate(num_features):
        for label, color in zip([0, 1], colors):
            subset = df[df['stroke'] == label][col].dropna()
            axes[i].hist(subset, bins=30, alpha=0.6, label=f'Stroke={label}',
                         color=color, edgecolor='black', linewidth=0.3)
        axes[i].set_title(f'{col} by Stroke Status', fontsize=12, fontweight='bold')
        axes[i].set_xlabel(col)
        axes[i].set_ylabel('Count')
        axes[i].legend()

        # Print mean comparison
        mean_0 = df[df['stroke'] == 0][col].mean()
        mean_1 = df[df['stroke'] == 1][col].mean()
        print(f"\n{col}: No-stroke mean={mean_0:.2f}, Stroke mean={mean_1:.2f}")

    plt.suptitle('Numerical Features by Stroke Status', fontsize=14, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, '04_bivariate_numerical.png'), bbox_inches='tight')
    plt.close()

    # --- Box plots: numerical vs stroke ---
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))

    for i, col in enumerate(num_features):
        data_0 = df[df['stroke'] == 0][col].dropna()
        data_1 = df[df['stroke'] == 1][col].dropna()
        bp = axes[i].boxplot([data_0, data_1], tick_labels=['No Stroke', 'Stroke'],
                              patch_artist=True)
        bp['boxes'][0].set_facecolor(colors[0])
        bp['boxes'][1].set_facecolor(colors[1])
        for box in bp['boxes']:
            box.set_alpha(0.7)
        axes[i].set_title(f'{col} by Stroke Status', fontsize=12, fontweight='bold')
        axes[i].set_ylabel(col)

    plt.suptitle('Box Plots: Numerical Features by Stroke', fontsize=14, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, '05_bivariate_numerical_boxplots.png'), bbox_inches='tight')
    plt.close()

    # --- Categorical features vs stroke ---
    cat_features = ['gender', 'hypertension', 'heart_disease', 'ever_married',
                    'work_type', 'smoking_status']

    fig, axes = plt.subplots(2, 3, figsize=(20, 12))
    axes = axes.flatten()

    for i, col in enumerate(cat_features):
        # Calculate stroke rate per category
        stroke_rate = df.groupby(col)['stroke'].mean().sort_values(ascending=False)

        axes[i].bar(range(len(stroke_rate)), stroke_rate.values,
                    color='#FF9800', edgecolor='black', linewidth=0.5)
        axes[i].set_xticks(range(len(stroke_rate)))
        axes[i].set_xticklabels(stroke_rate.index, rotation=30, ha='right')
        axes[i].set_title(f'Stroke Rate by {col}', fontsize=12, fontweight='bold')
        axes[i].set_ylabel('Stroke Rate')
        axes[i].set_ylim(0, max(stroke_rate.values) * 1.3)

        # Add value labels
        for j, v in enumerate(stroke_rate.values):
            axes[i].text(j, v + 0.005, f'{v:.3f}', ha='center', fontsize=9)

        print(f"\n{col} stroke rates:")
        for val, rate in stroke_rate.items():
            print(f"  {val}: {rate:.4f}")

    plt.suptitle('Stroke Rate by Categorical Features', fontsize=15, fontweight='bold', y=1.01)
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, '06_bivariate_categorical.png'), bbox_inches='tight')
    plt.close()


# ============================================================
# 6. Correlation Analysis
# ============================================================
def _correlation_analysis(df, output_dir):
    """Generate correlation heatmap for numerical/binary features."""
    print("\n--- Correlation Analysis ---")

    # Select numeric columns and encode binary categoricals for correlation
    df_corr = df.copy()
    df_corr['gender_encoded'] = df_corr['gender'].map({'Male': 0, 'Female': 1, 'Other': 2})
    df_corr['ever_married_encoded'] = df_corr['ever_married'].map({'No': 0, 'Yes': 1})
    df_corr['Residence_encoded'] = df_corr['Residence_type'].map({'Rural': 0, 'Urban': 1})

    corr_cols = ['age', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi',
                 'gender_encoded', 'ever_married_encoded', 'Residence_encoded', 'stroke']

    corr_matrix = df_corr[corr_cols].corr()

    plt.figure(figsize=(12, 10))
    mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
    sns.heatmap(
        corr_matrix, mask=mask, annot=True, fmt='.3f',
        cmap='RdBu_r', center=0, square=True,
        linewidths=0.5, cbar_kws={'shrink': 0.8}
    )
    plt.title('Correlation Heatmap', fontsize=15, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, '07_correlation_heatmap.png'), bbox_inches='tight')
    plt.close()

    # Print top correlations with stroke
    stroke_corr = corr_matrix['stroke'].drop('stroke').abs().sort_values(ascending=False)
    print("\nCorrelation with stroke (absolute values):")
    for feat, corr in stroke_corr.items():
        print(f"  {feat}: {corr:.4f}")


# ============================================================
# Standalone execution
# ============================================================
if __name__ == '__main__':
    from preprocessing import load_data
    df = load_data()
    run_eda(df)
